Navbar
MasumaJaffery/My-Portfolio pull request #1
Opened 2023-03-26 20:02 UTC by MasumaJaffery

2023-03-27 19:41 UTC, Zuhaib042 reviewed
Hi @MasumaJaffery , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive PR summary, kindly consider adding a descriptive pull request summary to your pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-27 21:05 UTC, levy002 reviewed
## Hello @MasumaJaffery 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that doesn't have a descriptive PR summary and PR title.

 - [ ] Kindly update your PR summary by providing a detailed summary so everyone knows what has been changed which will make your PR more clean and professional.

     ### EXAMPLE OF A GOOD PR SUMMARY
    ![image](https://user-images.githubusercontent.com/87197412/228065555-35fb6261-854b-4487-9dde-fd6ffc233fcd.png)

- [ ] Kindy make sure to edit your PR title and Provide a detailed one for everyone to understand easily what's going on in your feature branch. For example `Portfolio mobile setup` or `Portfolio mobile navigation and headline sections`

- [ ] Kindly make sure to remove all comments and guidelines of how README must be filled in order to keep your README clean and professional.

 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-27 22:46 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @MasumaJaffery 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 22:46 UTC, tresorsawasawa commented on index.html
> +<nav>
- [ ] As required for the project, kindly make sure the container of the your header is a `header` tag and not a section. Typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info

2023-03-27 22:46 UTC, tresorsawasawa commented on index.html
> +    <h4>My Logo</h4>
- [ ] Kindly make sure the logo text has a link (`a` tag). This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.The logo (if the design has one) is on the left and has a link (a tag).

2023-03-27 22:46 UTC, tresorsawasawa commented on index.html
> +</section>
- [ ] Kindly make sure your header design sticks as much as possible to the one from Figma design such as using the correct spacing at the left of the logo text and right of hamburger button.

| Figms Design | Your Design |
| ------------------- | ---------------- |
| ![Screenshot from 2023-03-27 18-21-19](https://user-images.githubusercontent.com/83042742/228080208-9083b3c2-a69b-4458-a7e1-5d07c02412b8.png) | ![Screenshot from 2023-03-27 18-23-45](https://user-images.githubusercontent.com/83042742/228080469-8ed0eac3-c274-43be-9c5e-bae15b0c1125.png) |

2023-03-27 22:46 UTC, tresorsawasawa commented on index.html
> +            Glad to see you!</h3>
- [ ] As required for the project, kindly make sure the main title (e.g., "I'm Marianne ...") is a `h1` tag instead of a `h3`a for good semantics. If you want that google (and other search engines) knows about a specific topic, in this case, you, use an `h1` tag. [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2023-03-27 22:46 UTC, tresorsawasawa commented on index.html
> +    </div>
- [ ] Kindly make sure, the list of icons uses a `ul` tag as container to group them, and `li` per icon; each icon has a link (a tag). Apart from being semantically correct, the a tag will let you connect your social networks with the icons, using `href` attribute of the the `a` tag. example:
```html
<ul>
  <li>
     <a href="..."><img src = "Images/Linkedin.png"></i></a>
  </li>
  <li>
     <a href="..."><img src = "Images/Linkedin.png"></i></a>
  </li>
  ...
</ul>
```

2023-03-27 22:46 UTC, tresorsawasawa commented on index.html
> +    </div>
- [ ] I think it would be better if you improve you improve your design to stick as much as possible to the one from Figma. This for project's requirements. **e.g.: Fonts-weight, spacing(padding & margin), alignment,...**

| Figma Design | Your Design |
| ------------ | ------------------- |
| ![Figma design](https://github.com/microverseinc/curriculum-html-css/raw/main/portfolio/images/m1_setup/headline-mobile.png) | ![Screenshot from 2023-03-27 18-36-22](https://user-images.githubusercontent.com/83042742/228082591-4cd1be2a-48fa-459c-8977-5d427cd13ad5.png) |

2023-03-27 22:46 UTC, tresorsawasawa commented on index.html
> +
- [ ] `README.md` file: I think it would be better if you improve your `Getting Started` section by adding all information needed in order to make your README documentation not descriptive and professional but also to help non technical users to help you on how to `setup`, `use`, `install`,... your repo locally. To help you, just refer this **[example](https://gist.github.com/tresorsawasawa/36552594cf13b97ffd7366e81b09dcfd)**

2023-03-28 11:49 UTC, algerina requested changes
Hi @MasumaJaffery  ,

Great job so far! 
However, you still have minor issues to fix.

May I highlight the following: 
- [x] Your project looks awesome👏  ✔️ 
- [x] No Linter errors✔️ 
- [x] Well done implementing most of the previous reviewer's requirements✔️ 



## STATUS: CHANGES REQUIRED ♻️ 
PLEASE: check the comments under the review

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-03-28 11:49 UTC, algerina commented on README.md
> +```
- [ ] You did a nice job improving the Readme however, the MIT license link is broken, kindly work on that issue.

2023-03-28 12:32 UTC, iambenkis approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 12:34 UTC, merged